#!/usr/bin/env bash
 
if bspc query -N -n focused.floating > /dev/null; then
    step=2
else
    step=100
f
 
case "$1" in
    west) dir=right; falldir=left; x="-$step"; y=0;;
    east) dir=right; falldir=left; x="$step"; y=0;;
    north) dir=top; falldir=bottom; x=0; y="-$step";;
    south) dir=top; falldir=bottom; x=0; y="$step";;
esac
 
bspc node -z "$dir" "$x" "$y" || bspc node -z "$falldir" "$x" "$y"
